### ISSUE TITLE
Throwing error 503 now.

### ISSUE THREAD

**Issue by Oznero** [OneLogicalMyth/DellWarranty#1]
Thank you for the work you've done.  Your module has helped keeping our assets up to date however it seems Dell has changed their URL.  Just wanted to let you know since its published in powershellgallery.

**Comment by OneLogicalMyth** [comment]
Thanks for your comment glad it served you well. :)

I have read the new API documentation and shouldn't be too hard to fix. Will work on it tonight.

**Comment by OneLogicalMyth** [comment]
I have requested a development key from Dell, once I have this I can update the code and test its working. Once all working I will push the changes to here and have the API as a configuration option for you to add yours.

You can get an API key from;
http://en.community.dell.com/dell-groups/supportapisgroup/
Strangely its in the PowerPoint file the email address to get in touch with them about it.

**Comment by OneLogicalMyth** [comment]
Code updated to support the new API provided by Dell, you will need to request an API key from them, this took 3 weeks for me. This has been tested on their sandbox API and all appears to be working, so should work for the production API also.
